language: python
python:
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: cosmoscalibur
  password:
    secure: iKEwv1hSvkKxAoch0pl763VyF3RHv2nyhgLEawX5FhTnQmCn8XEqPMMs1OUpkuZ3yfaJn1GF1ZxdaxKwom4YN2VVLwODpAlVitfRxQiaNNAcaJiLPEFDFwbWiSYWvOiY6uh5cx3EA6Pr0TNu7yH9ZZ6QewfG7bMVCLIinxcrggCsgRGSJcAOTV22mkaiNrTrPScc4iw5r+kEqkKjJ4XS+kBaLmJdcoZqFwaWVd0f7i2riCgqGO8PrVvAyjvM51ZzfdygnuV3KKQBRnZxtMlVh2U/sE3TFUpg7/B2N1nqy0mZYLoDqzvbp1u5s9a5kQXJ3sRgNwvvGro8at7P56Hni0hz+274+jEzb6K7+uPXGd91scmz6v/HNha391eV4STTCl/S+7+Aig1k83jUl2WjRwNil8qx4EyRnWMVmDnni3CgOTQ+oG8xTP3G2Aibi5jTpLAwnTzJ6A63ffZnOdekwv6nKlFsJEx+DaW3hvIgymcW+ONefSTwEbfNcCnY+irM9+tTTHTj+RFp5zz4zbfD0yHwKpRSl6ke0YPVHCAadrQym4meEbvEm5IImoHYR3x8EpINR5Phe+FOH185xRl0l+TrK0fVrS9MQ7xBP6/R2BqWYX4azcnXwZ9lW1IIpW8pgrA0UvDNxEjBDFHP0t5zC3pBVDpLRv+8C816m1B6jGg=
  on:
    tags: true
    repo: cosmoscalibur/moodlesg
    python: 3.6
