language: python
python:
- 3.6
- 3.5
- 3.4
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: bdist_wheel
  user: cosmoscalibur
  password:
    secure: WmEf501NC5+or434orL75oFAm3MSSH+oMKdc+V4qhHKQ0cR2Os43xqPK3Gf32zOoCE2KP0BkeVw5cBkX71cq2eBdXqNAPB7vXEDsSW/fvXnEe7mFhqONhFDW9X41d+1k7C+Cnh7IISaS5FP8ftjgpijCCGL3LSWk3moIf6yMaHNbPixi4CWIbtPIzODClk9YJW1DceG6l+qW6abdZykjRCL1mVDs3uCgzOJasarpFsLz+uY1kDbomAxmkIhQRVtXOEJ60UorArfeqkzKCRIeuhe7JEqe7cECvjf7Qt4KRCKvM68eB80nkAJgnhKulKfvm5mP5Vfv+SDS8GQ5df+X/OFx1oTumdy/noNcRAnO9AiArKlsjF8zAwZv2aaEgX1F3z75kO7toRZvde+doKlx/EBxGmEGmrmQSDrwbHPu3hIaRaG2M+68NGQlEZBh8+/GAFONfXz5C5ASftVHcEJcguCumTyei0xJI5x2DV0zdv/YkhkjehWfbivEgHyrbRYCwJOx4FFC5uxHrWTQZYzPw99lvDhmyDiL5NhnyeeulnkzttmNP/UpgLVwIwm0ElyRB4FKvpTyOoYRP9ZjVgr4u6jsBjmOEuGkvKBwwb7W0w9OPUw0qCsY2XCLFblp5HmDVrghwMIrDUDssmSNgqOUm15KwJaB2+W/+K2fQXqQ+wo=
  on:
    tags: true
    repo: cosmoscalibur/moodlesg
    python: 3.6
